<?php
function generateMetadataRow($metadataEntry) : string
{
    $html = '
    <tr>
        <td><b>'.$metadataEntry['key'].'</b></td>
        <td>';
    if ($metadataEntry['isObject']) {
        $html .= '<table class="striped-table">';
        foreach ($metadataEntry['value'] as $attribute) {
            $html .= generateMetadataRow($attribute);
        }
        $html .= '</table>';
    } else {
            $html .= $metadataEntry['value'];
    }
    $html .= '
        </td>
    </tr>';
    return $html;
}
?><h2>Informace o mikrobovi</h2>
<table class="striped-table">
    <?php foreach ($microbe_metadata as $metadataEntry) : ?>
        <?= generateMetadataRow($metadataEntry); ?>
    <?php endforeach ?>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr><td colspan="2"><b>Původce následujících onemocnění</b></td></tr>
    <?php foreach($microbe_conditions as $condition) : ?>
        <tr><td colspan="2">
            <a href="/onemocneni/<?= $condition->url ?>"><?= $condition->name ?></a>
        </td></tr>
    <?php endforeach ?>
</table>

<button id="new-metadata-button">Přidat metadata</button>
<form id="new-metadata-form" class="hidden" enctype="multipart/form-data" method="post" action="/api/metadata/add">
    <input type="hidden" name="microbe-id" value="<?= $microbe_id ?>">
    <input type="hidden" name="form-url" value="<?= $_SERVER['REQUEST_URI'] ?>">
    <h3>Přidat metadata</h3>
    <label for="new-metadata-key">Typ informace</label>
    <select id="new-metadata-key">
        <option disabled selected>Loading...</option>
    </select>
    <div id="new-metadata-value">
        <!-- Filled in by JavaScript -->
    </div>
</form>
<div class="hidden" id="data-holder" data-microbe-id="<?= $microbe_id ?>"></div>