<h2>Informace o mikrobovi</h2>
<table class="striped-table">
    <?php foreach ($microbe_metadata as $metadataEntry) : ?>
        <tr>
            <td><b><?= $metadataEntry['key'] ?></b></td>
            <td>
                <?php if ($metadataEntry['isObject']) : ?>
                    <table class="striped-table">
                        <?php foreach ($metadataEntry['value'] as $attribute) : ?>
                            <tr>
                                <td><b><?= $attribute['key'] ?></b></td>
                                <td><?= $attribute['value'] ?></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <?php else : ?>
                    <?= $metadataEntry['value'] ?>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<button id="new-metadata-button">Přidat metadata</button>
<form id="new-metadata-form" class="hidden">
    <h3>Přidat metadata</h3>
    <label for="new-metadata-key">Typ informace</label>
    <select id="new-metadata-key">
        <option disabled selected>Loading...</option>
    </select>
    <div id="new-metadata-value">
        <!-- Filled in by JavaScript -->
    </div>
</form>
<div class="hidden" id="data-holder" data-microbe-id="<?= $microbe_id ?>"></div>